version: '3.9'
services:
  postgres:
    image: 'postgres:alpine'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=elixir_gist
      - POSTGRES_PASSWORD=super_strong_password
      - POSTGRES_DB=elixir_gist_dev
volumes:
  postgres-volume:
networks:
  local:
    driver: bridge